services:
  redis:
    image: redis:7-alpine

  memcached:
    image: memcached:alpine

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  php:
    build:
      target: ext
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - redis
      - memcached
      - mysql
    stdin_open: true

  php-no-ext:
    build:
      target: no-ext
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - redis
      - memcached
      - mysql
    stdin_open: true
