name: Tests

on:
  push:

jobs:
  php-unit:
    name: PHP Unit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          docker compose up -d

      - name: Composer install
        run: composer install --optimize-autoloader --no-interaction --no-progress --prefer-dist --ignore-platform-reqs

      - name: PHPStan
        run: docker compose exec -t php vendor/bin/phpstan analyse src tests --memory-limit=256M

      - name: PHPcs
        run: docker compose exec -t php vendor/bin/phpcs src tests

      - name: Psalm
        run: docker compose exec -t php vendor/bin/psalm

      - name: Run phpunit (with extensions)
        run: docker compose exec -t php vendor/bin/phpunit tests/Unit/Extensions

      - name: Run phpunit (no extensions)
        run: docker compose exec -t php-no-ext vendor/bin/phpunit tests/Unit/NoExtensions
